In [ ]:
#Introduction to numpy:

In [ ]:
    Numpy will be acting as an foundational library in python.
    Majorly most of the libraries are built on top of numpy.

In [ ]:
Defination:
    Numpy is majorly used in the caclculation \computation of numerical data that will be processing.

In [ ]:
    Most of the scientific computation will be relying up on numpy only.

In [ ]:
#Installation of numpy: # !-->It will be executing syntax from terminal.

In [5]:
!pip install numpy

In [12]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\sanjay\anaconda3\lib\site-packages (1.19.1)


In [ ]:
#Understanding the datatype of numpy:

In [ ]:
Array---> It is internal Datatype provided by numpy.
 (Array is nothing but list)

In [ ]:
#what is the difference between Array & list? which one do you prefer.

In [ ]:
Array is better based on performance and execution.

In [ ]:
Reason:Internally it will be optimizing the data and saving space.
       Syntax execution will be implemented fast..!

In [17]:
#Syntax:
import numpy as np

In [ ]:
matrices-->n-dimensional arrays

In [18]:
#Req: creating an array with the list.
array_one=np.array([1,2,3,4,5])
print(array_one)

[1 2 3 4 5]


In [19]:
type(array_one)

numpy.ndarray

In [ ]:
#nd-->n dimensional array

In [20]:
numbers=[9,8,7,6]
array_two=np.array(numbers)
print(array_two)

[9 8 7 6]


In [ ]:
(x,y) x--> number of rows, y--> number of columns

In [21]:
array_of_zeros=np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
array_of_ones=np.ones((4,5))
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])