In [1]:
import numpy as np

In [2]:
array_of_zeros=np.zeros((3,4))

In [3]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
array_of_ones=np.ones((4,5))

In [5]:
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
type(array_of_ones)

numpy.ndarray

In [ ]:
Note: Internally numpy will be considering the float Datatype

In [ ]:
#req: To remove the dots...?

In [7]:
array_of_ones_int=np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [8]:
array_empty=np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Python-->range(startvalue,stopvalue,stepcount)
numpy-->arange

In [10]:
#req: To print the even numbers from 2 to 20 in numpy 

In [12]:
array_of_evens=np.arange(2,20,2) #last value is always exclusive
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
array_of_floats=np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
ndarrays---> n dimensional arrays

In [14]:
#Two dimensional arrays:

In [19]:
array_2d=np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [17]:
array_2d.shape

(2, 3)

In [ ]:
array=np.array