In [1]:
import numpy as np

In [2]:
#Printing the arrays:

In [ ]:
req: To create an array of 10 numbers...?

In [3]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#req:using reshape to create n dimensional arrays..?

In [5]:
array_nd=np.arange(10).reshape(2,5)
array_nd

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
array_nd.shape #(x,y)-->2 dimensional #(x,y,z)--->3dimnesional 

(2, 5)

In [7]:
array_nd=np.arange(10).reshape(3,6)
array_nd

ValueError: cannot reshape array of size 10 into shape (3,6)

In [ ]:
10----2,5 # 2*5=10

In [8]:
array_nd=np.arange(10).reshape(5,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
#1D array

In [10]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [11]:
a.shape #x-->10 array

(6,)

In [ ]:
#2D array

In [12]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
#3d array

In [14]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])