In [ ]:
3rd party libraries of python:

In [ ]:
python code-->15lines   Numpy-->4lines
(higher errors)        ( a lot more efficiency, with less errors in code)

In [1]:
import numpy as np--->alias name

In [ ]:
Numpy is offering a datatype called as an Array
N-dimensional array(ndarray)

In [ ]:
difference between an array and list?

In [ ]:
Numpy--> Numerical computations and also the scientific computations...

In [ ]:
#General syntax of an Numpy

In [ ]:
numpy.array(data,dtype,copy)

In [ ]:
#req: passing a list to an ndarray

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [4]:
array_of_zeros=np.zeros([2,3])
print(array_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
array_of_zeros=np.zeros((2,3))
print(array_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x,y(2,3)-->x=number of rows  y=number of columns