In [1]:
#Continuation of numpy

In [2]:
import numpy as np

In [3]:
#Arithmetic operations of numpy

In [15]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [16]:
a+b

array([15, 15, 15])

In [6]:
a-b

array([5, 5, 5])

In [7]:
a*b

array([50, 50, 50])

In [8]:
a/b

array([2., 2., 2.])

In [9]:
a<35  #Comparision

array([ True,  True,  True])

In [10]:
b<3

array([False, False, False])

In [ ]:
Modifying an existing array rather than create a new one

In [17]:
a*=3
a

array([30, 30, 30])

In [18]:
b+=a

In [19]:
b

array([35, 35, 35])

In [ ]:
Unary Operators

In [20]:
ages=np.array([12,15,18,20])

In [21]:
ages.min()

12

In [22]:
ages.max()

20

In [23]:
ages.sum()

65

In [24]:
numbers=np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
In a 2D array----> axis=0-->cols  axis=1-->rows

In [25]:
#req: TO get the sum of each cols

In [26]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [27]:
numbers.sum(axis=1)

array([ 6, 22, 38])